# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  bssapi:
    image: bssapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5133:5133
